//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLot.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotStay
    {
        public int LotStayKey { get; set; }
        public System.DateTime StartStay { get; set; }
        public Nullable<System.DateTime> EndStay { get; set; }
        public int KeyCardKey { get; set; }
        public int ParkingSpotKey { get; set; }
        public Nullable<decimal> StayCost { get; set; }
    
        public virtual KeyCard KeyCard { get; set; }
        public virtual ParkingSpot ParkingSpot { get; set; }
    }
}
